{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"Unexpected error:\n    <*shell.ErrWithCmdOutput | 0xc0009073f8>: {\n        Underlying: <*exec.ExitError | 0xc000623be0>{\n            ProcessState: {\n                pid: 6536,\n                status: 256,\n                rusage: {\n                    Utime: {Sec: 0, Usec: 300735},\n                    Stime: {Sec: 0, Usec: 138496},\n                    Maxrss: 103640,\n                    Ixrss: 0,\n                    Idrss: 0,\n                    Isrss: 0,\n                    Minflt: 6539,\n                    Majflt: 679,\n                    Nswap: 0,\n                    Inblock: 28600,\n                    Oublock: 20592,\n                    Msgsnd: 0,\n                    Msgrcv: 0,\n                    Nsignals: 0,\n                    Nvcsw: 1896,\n                    Nivcsw: 1554,\n                },\n            },\n            Stderr: nil,\n        },\n        Output: {\n            stdout: {\n                Lines: nil,\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/e2e/assets/controller/nodeaffinity/slicenodeaffinity_red_success.yaml\\\": Internal error occurred: failed calling webhook \\\"vslicenodeaffinity.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/validate-controller-kubeslice-io-v1alpha1-slicenodeaffinity?timeout=10s\\\": dial tcp 10.96.60.138:443: connect: connection refused\",\n                    ],\n                },\n            },\n            stderr: {\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/e2e/assets/controller/nodeaffinity/slicenodeaffinity_red_success.yaml\\\": Internal error occurred: failed calling webhook \\\"vslicenodeaffinity.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/validate-controller-kubeslice-io-v1alpha1-slicenodeaffinity?timeout=10s\\\": dial tcp 10.96.60.138:443: connect: connection refused\",\n                ],\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/e2e/assets/controller/nodeaffinity/slicenodeaffinity_red_success.yaml\\\": Internal error occurred: failed calling webhook \\\"vslicenodeaffinity.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/validate-controller-kubeslice-io-v1alpha1-slicenodeaffinity?timeout=10s\\\": dial tcp 10.96.60.138:443: connect: connection refused\",\n                    ],\n                },\n            },\n            merged: {\n                Mutex: {state: 0, sema: 0},\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/e2e/assets/controller/nodeaffinity/slicenodeaffinity_red_success.yaml\\\": Internal error occurred: failed calling webhook \\\"vslicenodeaffinity.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/validate-controller-kubeslice-io-v1alpha1-slicenodeaffinity?timeout=10s\\\": dial tcp 10.96.60.138:443: connect: connection refused\",\n                ],\n            },\n        },\n    }\n    error while running command: exit status 1; Error from server (InternalError): error when creating \"/e2e/assets/controller/nodeaffinity/slicenodeaffinity_red_success.yaml\": Internal error occurred: failed calling webhook \"vslicenodeaffinity.kb.io\": failed to call webhook: Post \"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/validate-controller-kubeslice-io-v1alpha1-slicenodeaffinity?timeout=10s\": dial tcp 10.96.60.138:443: connect: connection refused\noccurred","children":[{"name":"[It] Slice node affinity Tests SliceNodeAffinity tests - includes creation and deletion slice node affinity Passing - deletion of sliceconfig deletes the slicenodeaffinity","uid":"d8d18b8893975dab","parentUid":"623ee69f4ef130636f9b495ee9a7aa26","status":"failed","time":{"start":1693828311000,"stop":1693828387472,"duration":76472},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"623ee69f4ef130636f9b495ee9a7aa26"},{"name":"Timed out after 500.031s.\nExpected\n    <bool>: false\nto be true","children":[{"name":"[AfterSuite]","uid":"1f6d30ab5086eaff","parentUid":"b3546d3b50102c21d0116562c40a3be8","status":"failed","time":{"start":1693828311000,"stop":1693828850406,"duration":539406},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b3546d3b50102c21d0116562c40a3be8"},{"name":"Unexpected error:\n    <*shell.ErrWithCmdOutput | 0xc000906018>: {\n        Underlying: <*exec.ExitError | 0xc000622040>{\n            ProcessState: {\n                pid: 6553,\n                status: 256,\n                rusage: {\n                    Utime: {Sec: 0, Usec: 419542},\n                    Stime: {Sec: 0, Usec: 183073},\n                    Maxrss: 118684,\n                    Ixrss: 0,\n                    Idrss: 0,\n                    Isrss: 0,\n                    Minflt: 6549,\n                    Majflt: 172,\n                    Nswap: 0,\n                    Inblock: 30728,\n                    Oublock: 20624,\n                    Msgsnd: 0,\n                    Msgrcv: 0,\n                    Nsignals: 0,\n                    Nvcsw: 1893,\n                    Nivcsw: 2810,\n                },\n            },\n            Stderr: nil,\n        },\n        Output: {\n            stdout: {\n                Lines: nil,\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20resource%20quota%20Tests%20ResourceQuota%20creation%20tests%20Create%20ResourceQuota%20successful%20test877885790\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.60.138:443: connect: connection refused\",\n                    ],\n                },\n            },\n            stderr: {\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20resource%20quota%20Tests%20ResourceQuota%20creation%20tests%20Create%20ResourceQuota%20successful%20test877885790\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.60.138:443: connect: connection refused\",\n                ],\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20resource%20quota%20Tests%20ResourceQuota%20creation%20tests%20Create%20ResourceQuota%20successful%20test877885790\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.60.138:443: connect: connection refused\",\n                    ],\n                },\n            },\n            merged: {\n                Mutex: {state: 0, sema: 0},\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20resource%20quota%20Tests%20ResourceQuota%20creation%20tests%20Create%20ResourceQuota%20successful%20test877885790\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.60.138:443: connect: connection refused\",\n                ],\n            },\n        },\n    }\n    error while running command: exit status 1; Error from server (InternalError): error when creating \"/tmp/Slice%20resource%20quota%20Tests%20ResourceQuota%20creation%20tests%20Create%20ResourceQuota%20successful%20test877885790\": Internal error occurred: failed calling webhook \"msliceconfig.kb.io\": failed to call webhook: Post \"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\": dial tcp 10.96.60.138:443: connect: connection refused\noccurred","children":[{"name":"[It] Slice resource quota Tests ResourceQuota creation tests Create ResourceQuota successful test","uid":"ec22768c66be932f","parentUid":"31c0e8faee793b933243ba5a461dac59","status":"failed","time":{"start":1693828311000,"stop":1693828321536,"duration":10536},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"31c0e8faee793b933243ba5a461dac59"},{"name":"Timed out after 41.604s.\nExpected\n    <bool>: false\nto be true","children":[{"name":"[It] Events Test Events get recorded for slice config creation Validating events for slice resource quota config creation","uid":"ea71192651769640","parentUid":"53ca6d8f56d48be5510e7be9e92ca415","status":"failed","time":{"start":1693828311000,"stop":1693828443533,"duration":132533},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"53ca6d8f56d48be5510e7be9e92ca415"},{"name":"Timed out after 30.304s.\nUnexpected error:\n    <*json.SyntaxError | 0xc0009067c8>: {\n        msg: \"invalid character 'E' looking for beginning of value\",\n        Offset: 1,\n    }\n    invalid character 'E' looking for beginning of value\noccurred","children":[{"name":"[It] Slice RBAC Tests SliceRoleTemplate Tests Delete SliceRoleTemplate failure test: Deleting SliceRoleTempalate read-only-role participating in a SliceRoleBinding","uid":"b07869b300245a50","parentUid":"91f7e6558f78d02f00f43fbbd5d0f241","status":"failed","time":{"start":1693828311000,"stop":1693828410017,"duration":99017},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"91f7e6558f78d02f00f43fbbd5d0f241"},{"name":"Timed out after 200.002s.\nExpected\n    <int>: 1\nto be zero-valued","children":[{"name":"[It] E2E tests for license job > when Controller is upgraded license mode = manual should not launch a new license job","uid":"4fc1e94988e259b0","parentUid":"b37050dcf22187917bae18680359b9e0","status":"failed","time":{"start":1693828311000,"stop":1693828669599,"duration":358599},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b37050dcf22187917bae18680359b9e0"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}],"name":"categories"}