{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"Unexpected error:\n    <*shell.ErrWithCmdOutput | 0xc000471e18>: {\n        Underlying: <*exec.ExitError | 0xc0004aea60>{\n            ProcessState: {\n                pid: 5954,\n                status: 256,\n                rusage: {\n                    Utime: {Sec: 0, Usec: 275860},\n                    Stime: {Sec: 0, Usec: 121211},\n                    Maxrss: 107052,\n                    Ixrss: 0,\n                    Idrss: 0,\n                    Isrss: 0,\n                    Minflt: 16281,\n                    Majflt: 11,\n                    Nswap: 0,\n                    Inblock: 2048,\n                    Oublock: 18800,\n                    Msgsnd: 0,\n                    Msgrcv: 0,\n                    Nsignals: 0,\n                    Nvcsw: 697,\n                    Nivcsw: 1334,\n                },\n            },\n            Stderr: nil,\n        },\n        Output: {\n            stdout: {\n                Lines: nil,\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/tmp/4180828127\\\": Internal error occurred: failed calling webhook \\\"mcluster.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-cluster?timeout=10s\\\": dial tcp 10.96.86.179:443: connect: connection refused\",\n                    ],\n                },\n            },\n            stderr: {\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/tmp/4180828127\\\": Internal error occurred: failed calling webhook \\\"mcluster.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-cluster?timeout=10s\\\": dial tcp 10.96.86.179:443: connect: connection refused\",\n                ],\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/tmp/4180828127\\\": Internal error occurred: failed calling webhook \\\"mcluster.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-cluster?timeout=10s\\\": dial tcp 10.96.86.179:443: connect: connection refused\",\n                    ],\n                },\n            },\n            merged: {\n                Mutex: {state: 0, sema: 0},\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/tmp/4180828127\\\": Internal error occurred: failed calling webhook \\\"mcluster.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-cluster?timeout=10s\\\": dial tcp 10.96.86.179:443: connect: connection refused\",\n                ],\n            },\n        },\n    }\n    error while running command: exit status 1; Error from server (InternalError): error when creating \"/tmp/4180828127\": Internal error occurred: failed calling webhook \"mcluster.kb.io\": failed to call webhook: Post \"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-cluster?timeout=10s\": dial tcp 10.96.86.179:443: connect: connection refused\noccurred","children":[{"name":"[BeforeSuite]","uid":"e3e0f023e4169bc9","parentUid":"5650712559a018b6e073bb2cbde45d9d","status":"failed","time":{"start":1683567926000,"stop":1683567957488,"duration":31488},"flaky":true,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"5650712559a018b6e073bb2cbde45d9d"},{"name":"Timed out after 210.007s.\nExpected an error to have occurred.  Got:\n    <nil>: nil","children":[{"name":"[AfterSuite]","uid":"7e41e1d860c19ad4","parentUid":"ed472d1e401f756b9cf6c6e9b95d52ab","status":"failed","time":{"start":1683567926000,"stop":1683568136551,"duration":210551},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ed472d1e401f756b9cf6c6e9b95d52ab"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}],"name":"categories"}